CREATE TABLE V1_TIPOUSUARIOS (
  TIPU_UID NUMBER PRIMARY KEY,
  TIPU_NOMBRE VARCHAR2(50) NOT NULL
);

CREATE TABLE V1_USUARIOS (
  US_ID NUMBER PRIMARY KEY,
  US_USUARIO VARCHAR2(100) NOT NULL,
  US_CORREO VARCHAR2(120) NOT NULL,
  US_CONTRA VARCHAR2(100) NOT NULL,
  US_FREG DATE NOT NULL,
  US_ESTADO VARCHAR2(20) NOT NULL,
  US_TIPOUS NUMBER NOT NULL
);

ALTER TABLE V1_USUARIOS ADD CONSTRAINT UQ_USUARIO UNIQUE (US_USUARIO);

ALTER TABLE V1_USUARIOS ADD CONSTRAINT UQ_CORREO UNIQUE (US_CORREO);

ALTER TABLE V1_USUARIOS ADD CONSTRAINT FK_TIPOUS FOREIGN KEY (US_TIPOUS) REFERENCES V1_TIPOUSUARIOS(TIPU_UID);

CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;

CREATE TABLE V1_TIPODATACTOR (
  TP_DID NUMBER PRIMARY KEY,
  TP_NOMBRE VARCHAR2(50) NOT NULL
);

CREATE TABLE V1_DATACTORES (
  DAS_DID NUMBER PRIMARY KEY,
  DAS_UID NUMBER NOT NULL,
  DAS_TPDID NUMBER NOT NULL,
  DAS_VDATO VARCHAR2(255) NOT NULL
);

ALTER TABLE V1_DATACTORES ADD CONSTRAINT FK_DASUSID FOREIGN KEY (DAS_UID) REFERENCES V1_USUARIOS(US_ID);

ALTER TABLE V1_DATACTORES ADD CONSTRAINT FK_DASTIPODA FOREIGN KEY (DAS_TPDID) REFERENCES V1_TIPODATACTOR(TP_DID);

CREATE SEQUENCE SEQ_DACTORES START WITH 1 INCREMENT BY 1;

CREATE TABLE V1_PROY (
  PRO_ID NUMBER PRIMARY KEY,
  PRO_CAID NUMBER NOT NULL,
  PRO_TITULO VARCHAR2(255) NOT NULL,
  PRO_CANTACTORES NUMBER NOT NULL,
  PRO_DESC VARCHAR2(1000) NOT NULL,
  PRO_FECHACR DATE NOT NULL,
  PRO_FECHAIN DATE NOT NULL,
  PRO_FECHAFI DATE NOT NULL,
  PRO_ESTADO VARCHAR2(20) NOT NULL;

);

ALTER TABLE V1_PROY ADD CONSTRAINT FK_PROCAID FOREIGN KEY (PRO_CAID) REFERENCES V1_USUARIOS(US_ID);

CREATE SEQUENCE SEQ_PROYECTO START WITH 1 INCREMENT BY 1;

CREATE TABLE V1_PRO_SELE (
  PS_ID NUMBER PRIMARY KEY,
  PS_PROID NUMBER NOT NULL,
  PS_ACTID NUMBER NOT NULL,
  PS_FECHASEL DATE NOT NULL
);

ALTER TABLE V1_PRO_SELE ADD CONSTRAINT FK_PSPROID FOREIGN KEY (PS_PROID) REFERENCES V1_PROY(PRO_ID);

ALTER TABLE V1_PRO_SELE ADD CONSTRAINT FK_PSACID FOREIGN KEY (PS_ACTID) REFERENCES V1_USUARIOS(US_ID);

CREATE SEQUENCE SEQ_PROSEL START WITH 1 INCREMENT BY 1;

CREATE TABLE V1_AUD_PROYE (
  AUP_ID NUMBER PRIMARY KEY,
  AUP_PRO_ID NUMBER NOT NULL,
  AUP_PRO_TITULO VARCHAR2(255) NOT NULL,
  AUP_PRO_CANTACTORES NUMBER NOT NULL,
  AUP_FECHACR DATE NOT NULL,
  AUP_FECHAIN DATE NOT NULL,
  AUP_FECHAFI DATE NOT NULL,
  AUP_ESTADO VARCHAR2(20) NOT NULL
);

ALTER TABLE V1_AUD_PROYE ADD CONSTRAINT FK_AUPPROID FOREIGN KEY (AUP_PRO_ID) REFERENCES V1_PROY(PRO_ID);

CREATE TABLE V1_AUD_DATOACTOR (
  AUDAC_ID NUMBER PRIMARY KEY,
  AUDAC_UID NUMBER NOT NULL,
  AUDAC_TPDID NUMBER NOT NULL,
  AUDAC_VDATO VARCHAR2(255) NOT NULL, 
  AUDAC_FECHA DATE NOT NULL
);

CREATE SEQUENCE SEQ_AUD_DATOACTOR START WITH 1 INCREMENT BY 1;

ALTER TABLE V1_AUD_DATOACTOR ADD CONSTRAINT FK_AUDACUID FOREIGN KEY (AUDAC_UID) REFERENCES V1_USUARIOS(US_ID);

ALTER TABLE V1_AUD_DATOACTOR ADD CONSTRAINT FK_AUDACTPID FOREIGN KEY (AUDAC_TPDID) REFERENCES V1_TIPODATACTOR(TP_DID);
