CREATE TABLE V1_TIPOUSUARIOS (
  TIPU_UID NUMBER PRIMARY KEY,
  TIPU_NOMBRE VARCHAR2(50)
);

CREATE TABLE V1_USUARIOS (
  US_ID NUMBER PRIMARY KEY,
  US_USUARIO VARCHAR2(100),
  US_CORREO VARCHAR2(120),
  US_CONTRA VARCHAR2(100),
  US_FREG DATE,
  US_ESTADO VARCHAR2(20),
  US_TIPOUS NUMBER
);

ALTER TABLE V1_USUARIOS ADD CONSTRAINT UQ_USUARIO UNIQUE (US_USUARIO);

ALTER TABLE V1_USUARIOS ADD CONSTRAINT UQ_CORREO UNIQUE (US_CORREO);

ALTER TABLE V1_USUARIOS ADD CONSTRAINT FK_TIPOUS FOREIGN KEY (US_TIPOUS) REFERENCES V1_TIPOUSUARIOS(TIPU_UID);

CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;

CREATE TABLE V1_TIPODATACTOR (
  TP_DID NUMBER PRIMARY KEY,
  TP_NOMBRE VARCHAR2(50)
);

CREATE TABLE V1_DATACTORES (
  DAS_DID NUMBER PRIMARY KEY,
  DAS_UID NUMBER NOT NULL,
  DAS_TPDID NUMBER NOT NULL,
  DAS_VDATO VARCHAR2(255) NOT NULL
);

ALTER TABLE V1_DATACTORES ADD CONSTRAINT FK_DASUSID FOREIGN KEY (DAS_UID) REFERENCES V1_USUARIOS(US_ID);

ALTER TABLE V1_DATACTORES ADD CONSTRAINT FK_DASTIPODA FOREIGN KEY (DAS_TPDID) REFERENCES V1_TIPODATACTOR(TP_DID);

CREATE SEQUENCE SEQ_DACTORES START WITH 1 INCREMENT BY 1;

CREATE TABLE V1_PROY (
  PRO_ID NUMBER PRIMARY KEY,
  PRO_CAID NUMBER,
  PRO_TITULO VARCHAR2(255),
  PRO_CANTACTORES NUMBER,
  PRO_DESC VARCHAR2(1000),
  PRO_FECHACR DATE,
  PRO_FECHAIN DATE,
  PRO_FECHAFI DATE PRO_ESTADO VARCHAR2(20);

);

ALTER TABLE V1_PROY ADD CONSTRAINT FK_PROCAID FOREIGN KEY (PRO_CAID) REFERENCES V1_USUARIOS(US_ID);

CREATE SEQUENCE SEQ_PROYECTO START WITH 1 INCREMENT BY 1;

CREATE TABLE V1_PRO_SELE (
  PS_ID NUMBER PRIMARY KEY,
  PS_PROID NUMBER,
  PS_ACTID NUMBER,
  PS_FECHASEL DATE
);

ALTER TABLE V1_PRO_SELE ADD CONSTRAINT FK_PSPROID FOREIGN KEY (PS_PROID) REFERENCES V1_PROY(PRO_ID);

ALTER TABLE V1_PRO_SELE ADD CONSTRAINT FK_PSACID FOREIGN KEY (PS_ACTID) REFERENCES V1_USUARIOS(US_ID);

CREATE SEQUENCE SEQ_PROSEL START WITH 1 INCREMENT BY 1;

CREATE TABLE V1_AUD_PROYE (
  AUP_ID NUMBER PRIMARY KEY,
  AUP_PRO_ID NUMBER,
  AUP_PRO_TITULO VARCHAR2(255),
  AUP_PRO_CANTACTORES NUMBER,
  AUP_FECHACR DATE,
  AUP_FECHAIN DATE,
  AUP_FECHAFI DATE,
  AUP_ESTADO VARCHAR2(20)
);
CREATE SEQUENCE SEQ_AUD_PROYE START WITH 1 INCREMENT BY 1;

ALTER TABLE V1_AUD_PROYE ADD CONSTRAINT FK_AUPPROID FOREIGN KEY (AUP_PRO_ID) REFERENCES V1_PROY(PRO_ID);

CREATE TABLE V1_AUD_DATOACTOR (
  AUDAC_ID NUMBER PRIMARY KEY,
  AUDAC_UID NUMBER,
  AUDAC_TPDID NUMBER,
  AUDAC_VDATO VARCHAR2(255), 
  AUDAC_FECHA DATE
);

CREATE SEQUENCE SEQ_AUD_DATOACTOR START WITH 1 INCREMENT BY 1;

ALTER TABLE V1_AUD_DATOACTOR ADD CONSTRAINT FK_AUDACUID FOREIGN KEY (AUDAC_UID) REFERENCES V1_USUARIOS(US_ID);

ALTER TABLE V1_AUD_DATOACTOR ADD CONSTRAINT FK_AUDACTPID FOREIGN KEY (AUDAC_TPDID) REFERENCES V1_TIPODATACTOR(TP_DID);
