CREATE OR REPLACE TRIGGER DEL_UPD_DATACTORES AFTER
    UPDATE OR DELETE ON V1_DATACTORES FOR EACH ROW
DECLARE
    V_ACTION VARCHAR2(10);
BEGIN
    IF UPDATING THEN
        V_ACTION := 'UPDATE';
    ELSIF DELETING THEN
        V_ACTION := 'DELETE';
    END IF;

    INSERT INTO V1_AUD_DATOACTOR (
        AUDAC_ID,
        AUDAC_UID,
        AUDAC_TPDID,
        AUDAC_VDATO,
        AUDAC_FECHA
    ) VALUES (
        SEQ_AUD_DATOACTOR.NEXTVAL,
        :OLD.DAS_UID,
        :OLD.DAS_TPDID,
        :OLD.DAS_VDATO,
        SYSDATE
    );
END DEL_UPD_DATACTORES;
/