CREATE OR REPLACE TRIGGER DEL_UPD_DATACTORES AFTER
    UPDATE OR DELETE ON V1_DATACTORES FOR EACH ROW
DECLARE
    V_ACTION VARCHAR2(10);
BEGIN
    IF UPDATING THEN
        V_ACTION := 'UPDATE';
    ELSIF DELETING THEN
        V_ACTION := 'DELETE';
    END IF;

    INSERT INTO V1_AUD_DATOACTOR (
        AUDAC_ID,
        AUDAC_UID,
        AUDAC_TPDID,
        AUDAC_VDATO,
        AUDAC_FECHA
    ) VALUES (
        SEQ_AUD_DATOACTOR.NEXTVAL,
        :OLD.DAS_UID,
        :OLD.DAS_TPDID,
        :OLD.DAS_VDATO,
        SYSDATE
    );
END DEL_UPD_DATACTORES;
/


 
CREATE OR REPLACE TRIGGER V1_PROY_INSERT
AFTER INSERT ON V1_PROY
FOR EACH ROW
BEGIN
  INSERT INTO V1_AUD_PROYE (
    AUP_ID,
    AUP_PRO_ID,
    AUP_PRO_TITULO,
    AUP_PRO_CANTACTORES,
    AUP_FECHACR,
    AUP_FECHAIN,
    AUP_FECHAFI,
    AUP_ESTADO
  ) VALUES (
    SEQ_AUD_PROYE.NEXTVAL,
    :NEW.PRO_ID,
    :NEW.PRO_TITULO,
    :NEW.PRO_CANTACTORES,
    :NEW.PRO_FECHACR,
    :NEW.PRO_FECHAIN,
    :NEW.PRO_FECHAFI,
    :NEW.PRO_ESTADO
  );
END V1_PROY_INSERT_TRG;
/


CREATE OR REPLACE TRIGGER V1_PROY_UPDATE
BEFORE UPDATE ON V1_PROY
FOR EACH ROW
BEGIN
  -- Verifica si PRO_CANTACTORES ha cambiado
  IF :NEW.PRO_ESTADO IS NOT NULL AND :OLD.PRO_ESTADO != :NEW.PRO_ESTADO THEN 

    INSERT INTO V1_AUD_PROYE (
      AUP_ID,
      AUP_PRO_ID,
      AUP_PRO_TITULO,
      AUP_PRO_CANTACTORES,
      AUP_FECHACR,
      AUP_FECHAIN,
      AUP_FECHAFI,
      AUP_ESTADO
    ) VALUES (
      SEQ_AUD_PROYE.NEXTVAL,
      :OLD.PRO_ID,
      :OLD.PRO_TITULO,
      :OLD.PRO_CANTACTORES,
      :OLD.PRO_FECHACR,
      :OLD.PRO_FECHAIN,
      :OLD.PRO_FECHAFI,
      :NEW.PRO_ESTADO
    );
  END IF;
END V1_PROY_UPDATE;
/


CREATE OR REPLACE TRIGGER V1_PROSELE_INSERT
AFTER INSERT ON V1_PRO_SELE
FOR EACH ROW
DECLARE
  v_proyecto_id V1_PRO_SELE.PS_PROID%TYPE;
BEGIN
  -- Obtener el ID del proyecto insertado
  v_proyecto_id := :NEW.PS_PROID;

  UPDATE V1_PROY
  SET PRO_CANTACTORES = PRO_CANTACTORES + 1
  WHERE PRO_ID = v_proyecto_id;


EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLCODE || ' - ' || SQLERRM);
    ROLLBACK;
END V1_PROSELE_INSERT;
/
